public class MENU extends javax.swing.JFrame {

    /**
     * Creates new form MENU
     */
    public int i =0;
    public MENU() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        burger = new javax.swing.JButton();
        Meal = new javax.swing.JButton();
        Drinks = new javax.swing.JButton();
        Snacks = new javax.swing.JButton();
        PlaceOrder = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CartList = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        burger.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        burger.setLabel("Krabby Patty");
        burger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burgerActionPerformed(evt);
            }
        });
        getContentPane().add(burger, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 271, 332, 233));

        Meal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Meal.setLabel("MM and BB Meal");
        Meal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MealActionPerformed(evt);
            }
        });
        getContentPane().add(Meal, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 32, 332, 227));

        Drinks.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Drinks.setLabel("Kelp Shake");
        Drinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrinksActionPerformed(evt);
            }
        });
        getContentPane().add(Drinks, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 271, 376, 233));

        Snacks.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Snacks.setText("Krabby Fry");
        Snacks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SnacksActionPerformed(evt);
            }
        });
        getContentPane().add(Snacks, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 32, 376, 227));

        PlaceOrder.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        PlaceOrder.setLabel("Place Order");
        PlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaceOrderActionPerformed(evt);
            }
        });
        getContentPane().add(PlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, 293, 109));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Cart");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, 141, -1));

        CartList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(CartList, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, 240, 440));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wp2636472-spongebob-sky-background.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void burgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burgerActionPerformed
        BURGER b = new BURGER();    
        this.setVisible(false);
        b.setVisible(true);
            
    }//GEN-LAST:event_burgerActionPerformed

    private void MealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MealActionPerformed
        COMBOMEAL cm = new COMBOMEAL();
        this.setVisible(false);
        cm.setVisible(true);
    }//GEN-LAST:event_MealActionPerformed

    private void DrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrinksActionPerformed
        DRINKS d = new DRINKS();
        this.setVisible(false);
        d.setVisible(true);
    }//GEN-LAST:event_DrinksActionPerformed

    private void SnacksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SnacksActionPerformed
        SNACKS s = new SNACKS();
        this.setVisible(false);
        s.setVisible(true);
        
    }//GEN-LAST:event_SnacksActionPerformed

    private void PlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaceOrderActionPerformed
        RECEIPT r = new RECEIPT();
        this.setVisible(false);
        r.setVisible(true);
    }//GEN-LAST:event_PlaceOrderActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel CartList;
    private javax.swing.JButton Drinks;
    private javax.swing.JButton Meal;
    private javax.swing.JButton PlaceOrder;
    private javax.swing.JButton Snacks;
    private javax.swing.JButton burger;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
